name: Сергей Мелодин
title: Сергей Мелодин
description: "Писатель кода, статей, стихов."
url: https://melodyn.ru
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme_options:
  google_analytics: UA-146848421-1

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
