
name: Nithin Bekal
description: ''
url: http://nithinbekal.com
highlighter: pygments
permalink: /posts/:title
markdown: kramdown

theme:
  disqus_shortname: nithinbekal
  google_analytics: UA-2095438-7

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
